<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Tenant extends Authenticatable
{
    use HasFactory;

    protected $primaryKey = 'id_tenant';
    protected $keyType = 'string';
    public $incrementing = false;
    public $timestamps = false;
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->id_tenant = 'Tenant' . time();
        });
    }

    public function getAuthIdentifierName()
    {
        return 'id_tenant';
    }

    public function getAuthIdentifier()
    {
        return $this->getAttribute('id_tenant');
    }

    public function getAuthPassword()
    {
        return $this->getAttribute('password');
    }
}
